// ENUMS

const Types = Object.freeze({
  TEST: 'TEST',
  RESIZE: 'RESIZE',
  INPUT: 'INPUT',
  TEXT_ITEM: 'ADD_TEXT_ITEM',
  SHOW_PAGE_MODAL: 'SHOW_PAGE_MODAL',
  HIDE_PAGE_MODAL: 'HIDE_PAGE_MODAL',
  ADD_PAGE: 'ADD_PAGE',
  HIDE_PAGE_UI_BUTTONS: 'HIDE_PAGE_UI_BUTTONS',
  SHOW_PAGE_UI_BUTTONS: 'SHOW_PAGE_UI_BUTTONS',
  BEGIN_MERGE: 'BEGIN_MERGE',
  MERGE_PAGES: 'MERGE_PAGES'
})

export default Types
