// ENUMS

const Types = Object.freeze({
  TEST: 'TEST',
  RESIZE: 'RESIZE',
  INPUT: 'INPUT',
  INPUT_INBOOK: 'INPUT_INBOOK',
  HIDE_INPUT_INBOOK: 'HIDE_INPUT_INBOOK',
  TEXT_ITEM: 'ADD_TEXT_ITEM',
  TEXT_ITEM_INBOOK: 'ADD_TEXT_ITEM_INBOOK',
  SHOW_PAGE_MODAL: 'SHOW_PAGE_MODAL',
  HIDE_PAGE_MODAL: 'HIDE_PAGE_MODAL',
  ADD_PAGE: 'ADD_PAGE',
  HIDE_PAGE_UI_BUTTONS: 'HIDE_PAGE_UI_BUTTONS',
  SHOW_PAGE_UI_BUTTONS: 'SHOW_PAGE_UI_BUTTONS',
  // BEGIN_MERGE: 'BEGIN_MERGE'
  SHOW_CREATE_BOOK_MODAL: 'SHOW_CREATE_BOOK_MODAL',
  HIDE_CREATE_BOOK_MODAL: 'HIDE_CREATE_BOOK_MODAL',
  MERGE_PAGES: 'MERGE_PAGES'
})

export default Types
