// ENUMS

const Types = Object.freeze({
  TEST: 'TEST',
  RESIZE: 'RESIZE',
  INPUT: 'INPUT',
  INPUT_INBOOK: 'INPUT_INBOOK',
  HIDE_INPUT_INBOOK: 'HIDE_INPUT_INBOOK',
  TEXT_ITEM: 'ADD_TEXT_ITEM',
  TEXT_ITEM_INBOOK: 'ADD_TEXT_ITEM_INBOOK',
  SHOW_PAGE_MODAL: 'SHOW_PAGE_MODAL',
  HIDE_PAGE_MODAL: 'HIDE_PAGE_MODAL',
  ADD_PAGE: 'ADD_PAGE',
  HIDE_PAGE_UI_BUTTONS: 'HIDE_PAGE_UI_BUTTONS',
  SHOW_PAGE_UI_BUTTONS: 'SHOW_PAGE_UI_BUTTONS',
  SHOW_CREATE_BOOK_MODAL: 'SHOW_CREATE_BOOK_MODAL',
  HIDE_CREATE_BOOK_MODAL: 'HIDE_CREATE_BOOK_MODAL',
  MERGE_PAGES: 'MERGE_PAGES',
  ADD_PAGE_TO_EXISTING_BOOK: 'ADD_PAGE_TO_EXISTING_BOOK',
  UNSET_PAGE_ADDED: 'UNSET_PAGE_ADDED',
  DELETE_TEXT_ITEM: 'DELETE_TEXT_ITEM',
  DELETE_TEXT_ITEM_INBOOK: 'DELETE_TEXT_ITEM_INBOOK'
})

export default Types
